### ISSUE TITLE
[OS] 메모리

### ISSUE THREAD

**Issue by Do-yoon** [kakaotech-25/cs-plant-interview#10]
## 예상 면접 질문
* 메모리 계층에 대해 설명해보세요.
* 가상 메모리에 대해 설명해보세요.
* 페이지와 세그먼트의 차이를 설명해보세요.

**Comment by LEE-DA-EUN** [comment]
1. 메모리 계층에 대해 설명해보세요.
- 메모리 계층은 레지스터, 캐시, 메모리, 저장장치로 구성되어 있다.
- 레지스터는 CPU안에 있는 작은 메모리로 속도가 가장 빠르고 기억용량이 가장 적다.
- 캐시는 L1, L2 캐시를 지칭하며 속도가 빠르고 기억용량이 적다.
- 주기억장치는 RAM을 지칭하며 속도와 기억용량이 모두 보통이다.
- 보조기억장치는 HDD, SSD를 지칭하며 속도가 느리고 기억용량이 많다.
- 레지스터, 캐시, 주기억장치는 휘발성이지만 보조기억방치는 비휘발성이다.

2. 가상 메모리에 대해 설명해보세요.
- 가상 메모리는 메모리 관리 기법의 하나로 컴퓨터가 실제로 이용 가능한 메모리 자원을 추상화하여 이를 사용하는 사용자들에게 매우 큰 메모리로 보이게 만드는 것을 의미한다. 이 때 가상적으로 주어진 주소를 가상 주소라고 하며 실제 메모리상에 있는 주소를 실제 주소라고 한다. 가상 주소는 메모리관리장치에 의해 실제 주소로 변환되며 이 덕분에 사용자는 실제 주소를 의식할 필요없이 프로그램을 구축할 수 있게 된다.
- 가상 메모리는 가상 주소와 실제 주소가 매핑되어 있고 프로세스의 주소 정보가 들어 있는 페이지 테이블로 관리된다. 이때 속도 향상을 위해 메모리와 CPU 사이에 있는 주소 변환 캐시인 TLB를 사용한다.


3. 페이지와 세그먼트의 차이를 설명해보세요.
- 페이지는 가상 메모리를 사용하는 최소 크기의 단위이고 세그먼트는 의미 단위이다.

**Comment by 1013115** [comment]
1. 메모리 계층에 대해 설명해보세요.
    
    레지스터, 캐시, 메모리, 저장장치로 구성되어있으며 레지스터는 CPU안에 있는 작은 메모리로, 휘발성이며 속도가 가장 바르다. 캐시는 휘발성이며 속도가 빠르고 기억 용량이 적다. 주기억 장치는 RAM을 지칭하며 휘발성이고 속도, 기억 용량이 보통이다. 보조기억장치는 HDD, SSD를 일컬으며 비휘발성에 속도가 느리고 기억용량이 많다. 
    
2. 가상 메모리에 대해 설명해보세요.
    
    가상 메모리는 메모리 관리 기법의 하나로 컴퓨터가 실제로 이용 가능한 메모리 자원을 추상화하여 이를 사용하는 사용자들에게 매우 큰 메모리로 보이게 만드는 것을 말한다. 이때 가상적으로 주어진 주소를 가상 주소라고 하며, 실제 메모리상에 있는 주소를 실제 주소라고 한다. 가상 주소는 메모리관리 장치에 의해 실제 주소로 변환되며, 이 덕분에 사용자는 실제 주소를 의식할 필요 없이 프로그램을 구축할 수 있게 된다. 
    
3. 페이지와 세그먼트의 차이를 설명해보세요.
    
    페이지는 메모리를 동일한 크기의 블록으로 나눈 단위이다. 메모리 관리에서 페이지는 주로 가상 메모리에서 사용되며, 페이지 테이블을 통해 가상 주소를 물리 주소로 매핑한다. 세그먼트는 메모리를 서로 다른 크기의 논리적 단위로 나눈 것이다. 세그먼트는 프로세스의 논리적 구조에 맞게 나뉘며, 코드, 데이터, 스택 등의 서로 다른 세그먼트를 가질 수 있다.

**Comment by rimeir** [comment]
1. 메모리 계층은 레지스터, 캐시, 메모리, 저장장치로 구성되어있습니다. 레지스터는 CPU가 직접 데이터를 처리할 때 사용하는 임시 저장소입니다. CPU 안에 있는 작은 메모리로 휘발성이며 속도가 가장 빠르고 기억 용량이 가장 적습니다. 캐시는 자주 사용되는 데이터나 명령어를 저장하여 CPU가 빠르게 접근할 수 있도록 합니다. L1, L2, L3로 나뉘며 휘발성이며 속도가 빠르고  기억 용량이 적습니다. 주기억장치(RAM) 현재 실행 중인 프로그램과 운영체제가 사용하는 데이터를 저장합니다. 휘발성이며 속도와 기억 용량은 보통입니다. 보조기억장치는 HDD, SSD를 일컬으며 프로그램과 데이터를 장기적으로 저장할 때 사용합니다. 비휘발성이며 속도는 낮고 기억 용량이 큽니다.
2. 가상 메모리는 메모리 관리 기법 중 하나로 컴퓨터가 실제로 이용 가능한 메모리 자원을 추상화하여 이를 사용자들에게 매우 큰 메모리로 보이게 만드는 것 입니다. 가상으로 주어진 주소인 가상 주소는 메모리관리장치(MMU)에 의해 실제 메모리상에 있는 주소인 실제 조소를 변환되어 사용자가 실제 주소를 의식할 필요 없이 프로그램을 구축할 수 있습니다. 가상 메모리는 가상 주소와 실제 주소가 매핑되어 프로세스의 주소 정보가 들어있는 페이지 테이블로 관리합니다.
3. 페이지는 가상 메모리를 사용하는 최소 크기 단위로 고정 크기의 블록으로 메모리를 분할합니다. 세그먼트는 가변 크기의 논리적 단위로 메모리를 분할합니다.

**Comment by JaeJunday** [comment]
1. 레지스터, 캐시, 메모리, 저장장치로 구성됩니다.
2. 한정된 메모리크기를 추상화하여 사용자가 크게 느끼게 하는것을 의미합니다. 가상주소를 실제 주소에 매핑하여 실행하는 프로세스의 메모리를 RAM에 로드해줄 때 사용합니다.
3. 페이징은 메모리를 나눈 최소단위입니다. 세그먼트는 프로세스의 메모리를 논리적인 단위로 나눈것입니다.

**Comment by msung99** [comment]
1. 메모리 계층은 컴퓨터 시스템에서 다양한 속도와 용량을 가진 메모리들이 계층적으로 구성되어 있는 것을 의미한다. 높은 속도를 요구하는 작업에는 빠른 메모리를, 대량의 데이터를 저장할 떄는 느리지만 용량이 큰 메모리를 사용한다. 

또한 메모리 계층 구조는 다음과 같다.
- 레지스터 : CPU 내부에 있는 가장 빠른 메모리로, 프로세스거 직접 접근할 수 있다. 크기는 매우 작고, 속도는 가장 빠르다.
- 캐시 메모리 : 레지스터보다 크지만 메인 메모리보다는 작은 고속 메모리다. CPU 와 메인 메모리 사이에서 자주 사용되는 데이터를 저장해 접근 시간을 단축시킨다. L1, L2, L3 캐시로 구성되며, L1 이 가장 작고 빠르다.
- 메인 메모리 : 메모리 계층에서 CPU 가 직접 접근 가능한 메모리로, 작업 중인 프로그램과 데이터를 저장한다. 
- 보조 저장 장치 (Seccondary Storage) : HDD, SSD 와 같은 저장 장치이다. 용량이 크고 데이터의 영구 저장이 가능하지만, 메인 메모리보다 훨씬 느리다.

2. 가상 메모리 는 실행하고자 하는 프로그램을 일부만 메모리에 적재하여 실제 물리 메모리 크기보다 더 큰 프로세스를 실행할 수 있게 하는 기법이다. 이를 가능케 하는 가상 메모리 관리 기법으로는 페이징 과 세그먼테이션 이 있는데, 현대 대부분의 OS 가 사용하는 기법은 페이징이다. 페이징 기법을 사용하면 큰 프로세스를 실행할 수 있을 뿐만 아니라, 외부 단편화 문제도 해결할 수 있다.

3. 페이징은 한 프로세스를 페이지라는 같은 크기로 분할해서 보관하는 방식이라면, 세그먼테이션은 부위 별로 잘라서 보관한다고 이해하면 된다. 세그먼트는 의미가 같지 않은 논리적 내용을 기준으로 프로그램을 분할하기 때문에 분할된 각 세그먼트의 크기가 같지 않다.
