### ISSUE TITLE
[OS] 페이징과 세그먼테이션

### ISSUE THREAD

**Issue by msung99** [kakaotech-25/cs-plant-interview#11]
## 예상 면접 질문

- 스와핑(Swapping)의 장단점은 무엇인가요?
- First Fit, Best Fit, Worst Fit 메모리 할당 기법의 차이점은 무엇이며, 각 기법의 장단점에 대해 설명해보세요.
- 외부 단편화(External Fragmentation)와 내부 단편화(Internal Fragmentation)의 차이점은 무엇인가요?
- 페이징에서 발생할 수 있는 내부 단편화 문제를 설명하고, 이를 어떻게 해결할 수 있을지 설명해보세요.
- 페이징과 세그먼테이션의 차이점에 대해 설명해보세요.

### 관련 포스팅

https://haon.blog/cs/os/page-segmentation/

**Comment by LEE-DA-EUN** [comment]
1. 스와핑(Swapping)의 장단점은 무엇인가요?
- 장점 : 메모리 효율성을 높이고 다중 작업을 가능하게 하여 메모리 부족 문제를 완화할 수 있다.
- 단점 : 속도 저하와 스왑 스레싱으로 인해 성능이 저하될 수 있기에 과도한 스와핑은 오히려 시스템에 부담이 될 수 있다.

2. First Fit, Best Fit, Worst Fit 메모리 할당 기법의 차이점은 무엇이며, 각 기법의 장단점에 대해 설명해보세요.
**[First Fit]** 
- 빈 공간을 앞에서부터 순차대로 검색하다가 적재할 수 있는 공간을 발견하면 그 공간에 프로세스를 배치한다.
- 장점 : 검색 최소화 / 빠른 할당
- 단점 : Best Fit 방식에 비해 메모리 공간 낭비
**[Best Fit]** 
- 빈 공간을 모두 검색해본 후 프로세스가 적재될 수 있는 공간 중 가장 작은 공간에 프로세스를 배치한다.
- 장점 : 메모리 낭비가 가장 적음
- 단점 : 처음부터 끝까지 모두 탐색하기에 시간이 오래 걸림
**[Worst Fit]**
- 빈 공간을 모두 검색한 후 프로세스가 적재될 수 있는 공간 중 가장 큰 공간에 프로세스를 배치한다.
- 장점 : -
- 단점 : Best Fit 방식과 같이 모두 탐색하기에 시간이 오래 걸림 / 메모리 낭비가 심함

3. 외부 단편화(External Fragmentation)와 내부 단편화(Internal Fragmentation)의 차이점은 무엇인가요?
- 외부 단편화는 프로세스를 할당하기 어려울만큼 작은 메모리 공간들로 인해 메모리가 낭비되는 현상을 의미하고 내부 단편화는 할당된 메모리 블록 내에서 실제로 사용되지 않는 남은 공간이 낭비되는 현상을 의미한다.

4. 페이징에서 발생할 수 있는 내부 단편화 문제를 설명하고, 이를 어떻게 해결할 수 있을지 설명해보세요.
- 페이징은 외부 단편화 문제를 해결할 수 있지만 내부 단편화가 발생할 수 있다. 페이징은 프로세스의 논리 주소 공간을 페이지라는 일정한 크기 단위로 자르는데 모든 프로세스가 페이지 크기에 딱 맞게 잘리는 것은 아니기에 페이지 내부에서 아주 작은 빈 공간이 발생할 수 있다.
- 이를 해결하기 위해서는 세그멘테이션과 페이징을 결합하는 방식이 있다. 세그멘테이션으로 논리적인 단위로 메모리를 나누고 각 세그먼트를 다시 페이징하여 관리하면 세그먼트 내의 페이지들 간에는 내부 단편화가 줄어들 수 있다.

5. 페이징과 세그먼테이션의 차이점에 대해 설명해보세요.
- 페이징 방식은 프로세스를 일정한 크기의 페이지 단위로 분할하여 메모리에 적재하는 방식인 반면에 세그멘테이션 방식은 가상 메모리를 서로 크기가 다른 논리적 단위로 분할한 것을 의미한다.
- 페이징은 한 프로세스를 페이지라는 같은 크기로 분할해서 보관하는 방식이라면 세그멘테이션은 부위 별로 잘라서 보관한다.

**Comment by 1013115** [comment]
1. 스와핑(Swapping)의 장단점은 무엇인가요?
    - 메모리 사용의 효율성이 증가하며 메모리 공간이 부족한 경우에도 여러 프로세스를 동시에 실행할 수 있다. 프로세스가 필요로 하는 메모리가 물리 메모리보다 클 때, 스와핑을 통해 프로세스가 더 많은 가상 메모리를 사용할 수 있게 한다. 이는 큰 프로그램이 실행될 수 있도록 돕는다. 그러나 스와핑은 디스크 입출력(I/O) 작업을 수반하기 때문에, 물리 메모리에 비해 상대적으로 느린 디스크를 사용하게 되어 성능이 저하된다. 프로세스가 스와핑 아웃되었다가 다시 불러들여질 때, 디스크 I/O 시간이 추가로 발생한다.
2. First Fit, Best Fit, Worst Fit 메모리 할당 기법의 차이점은 무엇이며, 각 기법의 장단점에 대해 설명해보세요.
    - first fit은 os가 메모리 내의 빈 공간을 앞에서부터 순차대로 검색하다가 적재할 수 있는 공간을 발견하면 그 공간에 프로세스를 배치하는 방식이다. 프로세스가 적재될 수 있는 공간을 발견하는 즉시 메모리를 할당하므로, 검색을 최소화할 수 있고 결과적으로 빠른 할당이 가능하다. 그러나, best fit 방식에 비해 메모리 공간에 낭비가 심해질 수 있다.
    - Best Fit은 빈 공간을 모두 검색해 본 후, 프로세스가 적재될 수 있는 공간 중 가장 작은 공간에 프로세스를 배치하는 방식이다. 메모리 낭비가 가장 적다는 장점을 가지고 있지만, 처음부터 끝까지 모두 탐색하여 최적의 공간을 찾아내야 하므로, 시간이 오래걸린다.
    - worst fit은 OS 가 빈 공간을 모두 검색해 본 후, 프로세스가 적재될 수 있는 공간 중 가장 큰 공간에 프로세스를 배치하는 방식이다. 단점으로는 Best Fit 방식처럼 처음부터 끝까지 모두 탐색해야 하므로 시간이 오래걸린다. 또한 메모리 낭비까지 심하기 떄문에 가장 사용되지 않는 방식이다
3. 외부 단편화(External Fragmentation)와 내부 단편화(Internal Fragmentation)의 차이점은 무엇인가요?
    - 외부 단편화는 메모리 전체에서 여러 작은 블록들이 분산되어 있어 발생한다. 또한, 가변 크기 메모리 할당 방식에서 메모리의 해제로 인해 발생한다. 내부 단편화는 할당된 메모리 블록 내에서 사용되지 않는 공간이 발생한다. 또한 고정 크기 메모리 할당 방식에서 프로세스가 필요로 하는 크기보다 큰 메모리 블록이 할당될 때 발생한다.
4. 페이징에서 발생할 수 있는 내부 단편화 문제를 설명하고, 이를 어떻게 해결할 수 있을지 설명해보세요.
    - 내부 단편화는 하나의 페이지보다 작은 크기로 발생한다. 따라서 하나의 페이지 크기가 작다면 발생하는 내부 단편화 크기는 작아질 가능성이 크다. 하지만, 그렇다고 한 페이지의 크기를 너무 작게 설정해도 그마늠 페이지 테이블의 크기도 커지기 때문에, 페이지 테이블이 차지하는 공간이 낭비된다. 따라서 내부 단편화를 적당히 방지하면서, 너무 크지 않은 페이지 테이블이 만들어지도록 페이지의 크기를 조정하는 것이 바람직하다.
5. 페이징과 세그먼테이션의 차이점에 대해 설명해보세요.
    - 페이징은 한 프로세스를 페이지라는 같은 크기로 분할해서 보관하는 방식이라면, 세그먼테이션은 부위 별로 잘라서 보관한다고 이해하면 된다. 세그먼트는 의미가 같지 않은 논리적 내용을 기준으로 프로그램을 분할하기 때문에 분할된 각 세그먼트의 크기가 같지 않다.

**Comment by rimeir** [comment]
1. 스와핑의 장점으로는 현재 실행되지 않는 프로세스를 잠시 보조기억장치 일부 영역으로 쫓아내어 생긴 메모리사의 빈 공간에 다른 프로세스를 가져와 실행하여 메모리 절약할 수 있다는 점이 있습니다. 메모리 확장이 필요하거나 부족한 경우에도 프로세스를 동시에 실행할 수 있습니다. 스와핑의 단점으로는 보조기억장치가 일기/쓰기 속도가 비교적 느려 성능 저하가 발생합니다.
2. First Fit은 OS가 메모리내의 빈 공간을 앞에서부터 순차적으로 검색하다가 적재 가능한 공간을 찾으면 그 공간에 프로세스를 배치하는 방식입니다. 장점으로는 프로세스가 적재 가능한 공간을 발견하는 즉시 메모리를 할당하여 검색을 최소화하여 빠른 할당이 가능합니다. 단점으로는 크기에 상관없이 적재되어 Best Fit 방식에 비해 메모리 공간에 낭비가 심해질 수 있습니다. Best Fit은 빈 공간을 모두 검색해 프로세스가 적재될 수 있는 공간 중 가장 작은 공간에 배치하는 방식입니다. 장점으로는 메모리 낭비가 가장 적고 단점으로는 모두 탐색해야하므로 시간이 오래걸립니다. Worst Fit은 OS가 빈 공간을 모두 검색한 후 Best Fit과 달리 프로세스가 적재될 수 있는 공간 중 가장 큰 공간에 배치합니다. 따라서 Best Fit처럼 시간이 오래걸리고 가장 큰 공간에 프로세스를 적재하여 메모리 낭비도 심하다는 단점이 있습니다.
3. 외부 단편화는 프로세스를 할당하기 어려울만큼 작은 메모리 공간들로 인해 메모리가 낭비되는 현상입니다. 내부 단편화는 메모리 할당 시 프로세스가 필요한 크기보다 더 큰 메모리가 할당되어 사용되지 않는 메모리 공간이 생겨 메모리가 낭비되는 현상입니다.
4. 페이징은 프로세스의 논리 주소 공간을 고정 크기 단위인 페이지로 자르지만 모든 프로세스가 페이지 크기에 맞게 잘리지 않습니다. 따라서 페이지 내부에 작은 빈 공간이 발생할 수 있습니다. 내부 단편화는 하나의 페이지보다 작은 크기로 발생하여 한 페이지 크기가 작으면 내부 단편화 크기는 작아질 수 있습니다. 하지만 한 페이지의 크기가 너무 작아도 그만큼 페이지 테이블의 크기도 커져 페이지 테이블이 차지하는 공간이 낭비되는 문제도 발생합니다. 따라서 내부 단편화를 적당히 방지하면서 너무 크지 않는 페이지 테이블이 만들어지도록 페이지의 크기를 조정하여 해결합니다.
5. 페이징은 프로세스를 고정 크기의 페이지 단위로 분할하여 메모리에 적재하는 방식입니다. 세그먼테이션은 가상 메모리를 가변적은 크기의 논리적 단위인 세그먼트로 분할하여 메모리에 적재하는 방식입니다.

**Comment by JaeJunday** [comment]
- 스와핑은 메모리를 여러 프로세스가 효율적으로 같이사용할 수 있습니다. 스와핑이 잦아지면 스레싱이일어납니다.
-  할당기법에 따라 내부단편화 외부단편화가 일어날수있습니다.
- 외부단편화는 프로세스가 쓰고 남은 공간이 쪼개져 쓰기 힘든현상이고, 내부단편화는 더 작은공간에 할당돼서 프로세스의 일부를 사용하지 못하는 상태입니다.
- 세그멘테이션기법하고 섞어서 페이징세그멘테이션을 사용합니다.
