### ISSUE TITLE
[OS] TLB(Translation Lookaside Buffer)

### ISSUE THREAD

**Issue by 1013115** [kakaotech-25/cs-plant-interview#12]
## 예상 면접 질문

- TLB(Translation Lookaside Buffer)란 무엇인가요?
- TLB 히트(TLB Hit)와 TLB 미스(TLB Miss)가 무엇인지 설명해 주세요. 각각의 경우 시스템 성능에 어떤 영향을 미치나요?
- TLB의 크기가 작을 경우 어떤 문제가 발생할 수 있나요?

**Comment by LEE-DA-EUN** [comment]
1. TLB(Translation Lookaside Buffer)란 무엇인가요?
- CPU 내부에 존재하는 고속 캐시 메모리로, 가상 메모리 시스템에서 가상 주소를 물리 주소로 변환하는데 사용되는 페이지 테이블의 일부를 저장함
- 페이지 테이블 조회 시간을 단축시켜 메모리 접근 성능을 향상시키는데 중요한 역할을 함

2. TLB 히트(TLB Hit)와 TLB 미스(TLB Miss)가 무엇인지 설명해 주세요. 각각의 경우 시스템 성능에 어떤 영향을 미치나요?
- TLB 히트 :  페이지 번호가 TLB에 이미 저장되어 있는 경우 / 해당 프레임을 즉시 알수있어 메모리 접근이 빨라 시스템 성능이 향상됨
- TLB 미스 :  페이지 번호가 TLB에 없는 경우 / 페이지 테이블을 조회하여 물리주소를 찾아야 하고 이 과정에서 추가작업이 발생하기에 시스템 성능에 좋지 않음

3. TLB의 크기가 작을 경우 어떤 문제가 발생할 수 있나요?
- CPU가 자주 엑세스해야 하는 페이지를 모두 TLB에 포함할 수 없기에 TLB미스가 자주 발생하고 프로세스 실행속도에 오버헤드를 가져올 수 있음

**Comment by JaeJunday** [comment]
> TLB(Translation Lookaside Buffer)란 무엇인가요?
- MMU에서 사용되는 고속 캐시메모리입니다. 메모리 매핑에 사용되는 페이지테이블의 일부를 저장합니다.

> TLB 히트(TLB Hit)와 TLB 미스(TLB Miss)가 무엇인지 설명해 주세요. 각각의 경우 시스템 성능에 어떤 영향을 미치나요?
- 가상주소를 물리주소로 매핑하려고 할때 tlb에 필요한 내용이 있으면 히트, 없는 경우 페이지테이블을 다시 참조해야하는데 TLB미스라고 부릅니다.

> TLB의 크기가 작을 경우 어떤 문제가 발생할 수 있나요?
- TLB에 필요한 내용이 없어서 TLB미스가 날 확률이 높아지고 가상주소를 물리주소로 변환하는 성능이 떨어지게 됩니다.

**Comment by rimeir** [comment]
1. TLB는 CPU 내부에 존재하는 고속 캐시 메모리입니다. 가상 메모리 시스템에서 가상 주소를 물리 주소로 변환하는 데 사용되는 페이지 테이블의 일부를 저장합니다. 따라서 주소 변환 캐시라고도 하며 프로세서의 메모리 관리 장치(MMU)의 일부입니다.
2. TLB 히트는 메모리 관리 장치(MMU)가 필요한 페이지 번호를 TLB에서 찾은 경우를 말합니다. TLB 미스는 페이지 번호가 TLB에 없는 경우를 말합니다. TLB 히트율이 높으면 메인 메모리에 접근할 필요가 없어 시스템 성능이 좋고, TLB 미스율이 높으면 추가적인 메모리 접근이 필요하여 성능이 저하됩니다.
3. TLB의 크기가 작으면 저장할 수 있는 페이지 테이블 항목 수가 제한되어 TLB 미스가 증가하여 메모리 접근 속도가 저하됩니다.

**Comment by msung99** [comment]
1. TLB(Translation Lookaside Buffer)는 CPU에서 사용하는 일종의 캐시 메모리다. 메모리 주소를 변환하는 데 걸리는 시간을 줄이려고 사용한다.
2. TLB 히트(TLB Hit)는 CPU가 변환하려는 가상 주소가 TLB에 이미 저장되어 있어서 빠르게 실제 주소로 변환할 수 있는 경우다.
3.  TLB 크기가 작으면, 캐시에 저장할 수 있는 주소 변환 정보의 양이 줄어든다. 그 결과 TLB 미스가 더 자주 발생하게 되고, CPU가 페이지 테이블을 확인하는 일이 많아져서 시스템 성능이 더 나빠질 수 있게된다. 큰 TLB가 더 많은 정보를 담을 수 있어서 TLB 히트를 늘리고 미스를 줄여주는 역할을 한다.
