### ISSUE TITLE
[OS] CPU스케줄링

### ISSUE THREAD

**Issue by LEE-DA-EUN** [kakaotech-25/cs-plant-interview#13]
- 선점 스케줄링과 비선점 스케줄링의 차이점에 대해 설명해주세요.
- 기아현상은 어떤 상황을 의미하며 어떤 스케줄링 알고리즘에서 발생할 수 있는지 설명해주세요.
- 실시간 시스템의 경우에는 어떤 스케줄링 알고리즘을 사용하는 게 적합할까요?

**Comment by JaeJunday** [comment]
> 선점 스케줄링과 비선점 스케줄링의 차이점에 대해 설명해주세요.

- CPU가 동작할때 하나의 작업이 다른작업이 완료되기전에 CPU의 제어권을 뺏어서 동작할 수 있는 것이 선점형 스케줄링이고, 하나의 작업이 완전히 수행된뒤에 다음 작업이 수행되는것이 비선점형 스케줄링입니다.

> 기아현상은 어떤 상황을 의미하며 어떤 스케줄링 알고리즘에서 발생할 수 있는지 설명해주세요.

- 비선점 혹은 선점형 스케줄링 모두에서 발생할 수 있으며 작업이 무겁거나 혹은 특정이유로 우선순위가 낮아져 계속 자원이 할당되지 않는 상태를 의미합니다. SJF의 경우 오래걸리는 작업이 뒤로 미뤄지고, 우선순위 알고리즘에서는 우선순위가 낮은 프로세스가 기아상태에 빠질수있습니다.

> 실시간 시스템의 경우에는 어떤 스케줄링 알고리즘을 사용하는 게 적합할까요?
- 선점형 스케줄링 방식을 사용해서 작업이 계속 유기적으로 진행되도록 해주고, 그 뒤에는 우선순위를 정하기 위해 작업의 주기가 일정한 편인지, 마감기간이 중요한지 등등의 기준에 따라 나눌 수 있습니다.

**Comment by rimeir** [comment]
1. 선점 스케줄링은 프로세스가 CPU를 사용하고 있는 도중 더 중요한 작업이 발생하거나 우선순위가 높은 프로세스에서 CPU를 강제로 빼앗아 다른 프로세스에게 할당하는 방식입니다. 반면 비선점 스케줄링은 선점 스케줄링과 달리 한번 CPU를 할당받은 프로세스가 I/O 작업을 요청하거나 작업이 끝날 때까지 CPU를 계속해서 점유하는 방식으로 중간에 다른 프로세스가 CPU를 빼앗을 수 없습니다.
2. 기아현상은 여러 프로세스가 부족한 자원을 점유하기 위해 특정 프로세스가 영원히 자원(CPU)을 할당받지 못하는 상황을 의미합니다. 이는 남은 시간이 짧은 프로세스를 할당하는 SRT 스케줄링과 CPU 버스트 시간이 가장 짧은 프로세스를 할당하는 SJF 스케줄링, 우선순위를 부여하여 높은 프로세스를 할당하는 Priority 스케줄링에서 발생합니다.
3. 실시간 시스템은 우선순위 외에 마감시간이나 작업의 주기와 같은 고려사항이 있습니다. 따라서 마감시간을 고려하는 정적 우선순위(RM) 스케줄링과 작업의 주기를 고려하는 동적 우선순위(EDF) 스케줄링이 실시간 시스템이 사용하기 적합한 알고리즘입니다.

**Comment by msung99** [comment]
1. 선점 스캐쥴링과 비선점 스캐쥴링의 차이점은 프로세스가 CPU 를 사용하는 도중에 다른 프로세스가 해당 CPU 를 가져갈 수 있느냐 없느냐에 있다.

선점 스캐쥴링은 CPU 를 사용중인 프로세스가 있더라도 우선순위가 더 높은 다른 프로세스가 생기면 CPU 를 뺏어서 그 프로세스가 넘겨주는 방식이다. 라운드 로빈, 우선순위 스캐쥴링등이 이에 속한다.

반면 비선점 스캐쥴링은 한 번 CPU 를 점유한 프로세스가 자기 일을 끝낼 때까지, 다른 프로세스가 해당 CPU 를 가져갈 수 없는 방식이다. FIFO 나 SJF 가 이에 속한다.

2. 기아현상은 우선순위가 낮은 프로세스가 계속해서 CPU 를 할당받지 못하는 상황을 뜻한다. 예를들어, 우선순위 스캐쥴링에서 높은 우선순위를 가진 프로세스들이 계속해서 들어오면, 낮은 우선순위 프로세스는 CPU 를 할당받을 기회가 없어서 무한정 댁시 상 태가 머무를 수 있게된다. 이게 바로 기아현상이다.

3. 실시간 시스템에서는 정해진 시간내에 작업을 반드시 끝내야 하기 떄문에, 주로 우선순위 기반의 선점  스캐쥴링 알고리즘을 사용하는 것이 적합하다.

**Comment by 1013115** [comment]
1. 선점 스케줄링과 비선점 스케줄링의 차이점에 대해 설명해주세요.
- 선점 스케줄링은  CPU가 이미 실행 중인 프로세스를 강제로 중단시키고, 더 높은 우선순위를 가진 다른 프로세스에게 CPU를 할당할 수 있습니다.
- 비선점 스케줄링은  CPU가 한 번 프로세스에 할당되면, 해당 프로세스가 완료되거나 자발적으로 CPU를 반납할 때까지 다른 프로세스가 CPU를 사용할 수 없습니다.

2. 기아현상은 어떤 상황을 의미하며 어떤 스케줄링 알고리즘에서 발생할 수 있는지 설명해주세요.
-  특정 프로세스가 필요한 자원을 할당받지 못해 오랜 시간 동안 대기하는 상황을 의미하며 우선순위가 낮은 프로세스가 높은 우선순위의 프로세스들에 의해 계속해서 CPU 사용이 뒤로 밀릴 때 발생한다. 기아현상을 방지하기 위해 에이징 기법을 사용할 수 있다. 

3. 실시간 시스템의 경우에는 어떤 스케줄링 알고리즘을 사용하는 게 적합할까요?
- 실시간 시스템에서는 특정 작업이 정해진 시간 내에 반드시 완료되어야 하기 때문에 응답시간과 시간 제약이 매우 중요하다. 이런 요구를 충족시키기 위해 주기가 짧으 작업일 수록 높은 우선순위를 부여하는 RM, 가장 마감시한이 임박한 작업에 우선순위를 부여하는 EDF 등을 사용할 수 있다.
