### ISSUE TITLE
[Network] ILB(Internal Load Balancer)

### ISSUE THREAD

**Issue by rimeir** [kakaotech-25/cs-plant-interview#16]
## 예상 면접 질문

- ILB가 무엇이고 ELB와의 차이점에 대해 설명해주세요.
- ILB 알고리즘을 각각 설명해주세요.

**Comment by LEE-DA-EUN** [comment]
1. ILB가 무엇이고 ELB와의 차이점에 대해 설명해주세요.
ILB는 내부로드밸런서로 클라우드 환경에서 내부 네트워크 내에서만 접근 가능한 로드밸런서로 내부 리소스 간의 트래픽을 분산 처리하는 역할을 수행합니다. 외부에 노출되지 않은 내부 서비스 간의 효율적인 통신과 트래픽 관리로 네트워크 성능 최적화 및 서비스 가용성을 보장합니다.
반면에 ELB는 외부로드밸런서로 인터넷에서 들어오는 외부 트래픽을 처리하는데 ILB와 달리 외부 네트워크와의 통신을 처리하는데 사용합니다.

2. ILB 알고리즘을 각각 설명해주세요.
- 라운드로빈 : 서버목록을 순환하며 들어오는 요청 순서대로 서버 그룹에 요청을 분배하여 모든 서버에 트래픽이 균등하게 분배되도록 함
- 소스 IP해시 : 로드 밸런서가 수신 요청의 소스 IP를 기준으로 특정 서비를 선택하고 특정 IP주소를 가진 클라이언트는 항상 동일한 서버로 연결
- 소스 IP 및 포트 해시 : 로드 밸런서가 수신 요청의 소스 IP주소 및 소스 포트에 대한 해시 값을 기반으로 선택
- 소스 IP 및 VIP 해시 : 로드 밸런서가 수신 요청의 소스 IP주소 및 VIP에 대한 해시값을 기반으로 서버를 선택하여 클라이언트가 다양한 서비스를 요청할 때 특정 서비스에 대해 일관된 서버를 선택하는데 사용

**Comment by JaeJunday** [comment]
> ILB가 무엇이고 ELB와의 차이점에 대해 설명해주세요.
- ILB는 내부 네트워크에서 사용하는 로드 밸런서입니다. 데이터베이스 서버나 애플리케이션 서버등의 트래픽을 분산하는데 사용됩니다. ELB와의 가장 큰 차이점은 외부네트워크에서 접근할수 없다는 점이 다릅니다.
> ILB 알고리즘을 각각 설명해주세요.
- 라운드로빈 : 트래픽을 순차적으로 균등하게 분배합니다.
- 소스IP해시 : 소스 IP주소를 기준으로 특정 동일서버 선택합니다.
- 소스IP및 포트해시 : 해시값을 기반으로 서버를 선택합니다.
- 소스 IP 및 VIP 해시 : VIP와 소스IP 해시 기반으로 서버를 선택합니다.

**Comment by msung99** [comment]
1. ILB: 내부 서비스 간의 트래픽 분산. / ELB: 외부 트래픽을 여러 서버에 분산.
2. 라운드 로빈 (Round Robin): 순차적으로 서버에 트래픽 분배.
최소 연결 (Least Connections): 현재 연결이 적은 서버에 트래픽 분배.
최소 응답 시간 (Least Response Time): 응답 시간이 빠른 서버에 트래픽 분배.
해시 기반 (Hash-Based): 특정 요소를 해시해 일관된 서버로 트래픽 분배.

**Comment by 1013115** [comment]
1. ILB가 무엇이고 ELB와의 차이점에 대해 설명해주세요.
- ILB는 내부 네트워크에서의 트래픽을 관리 및 분산처리하며 ELB는 인터넷에서 들어오는 외부 트래픽을 처리한다.
2. ILB 알고리즘을 각각 설명해주세요.
- 라운드로빈은 서버 목록을 순환하며 들어오는 요청 순서대로 서버 그룹에 요청을 지정(분배)하고 서버에 요청이 지정되면 서버 목록 끝으로 서버 이동 -> 요청 받은 서버가 다음 순번에서 제외 -> 나머지 서버들이 먼저 요청을 받는다. 모든 서버에 트래픽이 균등하게 분배된다.
- 소스 IP 해시는 로드 밸런서가 수신 요청의 소스 IP 주소를 기준으로 특정 서버 선택하고 특정 IP 주소를 가진 클라이언트는 항상 동일한 서버로 연결한다.
- 소스 IP 및 포트 해시는 로드 밸런서가 수신 요청의 소스 IP 주소 및 소스 포트에 대한 해시 값을 기반으로 서버 선택하고 동일한 IP에서 다양한 애플리케이션을 사용하는 경우 유용하다.
- 소스 IP 및 VIP 해시는 로드 밸런서가 수신 요청의 소스 IP 주소 및 VIP(Virtual IP)에 대한 해시 값을 기반으로 서버 선택하고 클라이언트가 다양한 서비스(VIP)를 요청할 때 특정 서비스에 대해 일관된 서버를 선택하는 데 사용한다.
