### ISSUE TITLE
[Network] OSI 7계층

### ISSUE THREAD

**Issue by LEE-DA-EUN** [kakaotech-25/cs-plant-interview#19]
## 예상 면접 질문

- 전송계층에서 TCP와 UDP의 차이점을 설명해주세요
- IP주소와 MAC주소가 필요한 이유를 설명해주세요

**Comment by 1013115** [comment]
1. 전송계층에서 TCP와 UDP의 차이점을 설명해주세요
- TCP는 패킷 교환 방식을 사용하며 신뢰성있는 통신을 하고, UDP는 데이터 그램 방식을 사용하며 빠른 전송을 제공하나 비신뢰성 전송이다.

2. IP주소와 MAC주소가 필요한 이유를 설명해주세요
- 네트워크 계층에서  IP주소를 사용하여 패킷의 올바른 목적지인지 확인하기 때문이다. 또한 MAC  주소 확인을 통해 데이터링크 계층에서올바르게 수신된 데이터를 확인한다.

**Comment by rimeir** [comment]
1. TCP와 UDP는 송신자와 수진자 사이의 데이터 전송을 담당하는 전송 계층의 프로토콜입니다. TCP는 신뢰성이 높지만 전송 속도가 느리며, UDP는 빠를 전송을 제공하나 비신뢰성인 전송을 합니다.
2. IP주소는 네트워크 계층에서 패킷이 올바른 경로로 전송되었는지 확인하는데 사용하고, MAC주소는 데이터링크 계층에서 로컬 네트워크 내에서 데이터를 올바른 장치로 전달할때 사용합니다.

**Comment by JaeJunday** [comment]
1. TCP는 연결지향형 프로토콜이고, UDP는 비연결 지향형입니다. tcp 같은 경우에 패킷을 안정적으로 전달하기 위한 handshake과정이 있고 udp는 없어서 더 빠릅니다. tcp는 오류제어, 혼잡제어, 흐름제어 등을 제공합니다.
2. IP주소는 공용 IP주소와 사설 IP주소로 나눌 수 있고 인터넷에서 식별가능한 가장 작은 단위의 단말입니다. MAC주소는 arp프로토콜에서 장치식별자로 사용되며 패킷을 어느 장비로 보낼지 식별할때 사용합니다.

**Comment by msung99** [comment]
1. TCP와 UDP의 차이점

- TCP (Transmission Control Protocol): 연결 지향형 프로토콜로, 데이터의 전송 보장과 순서 보장을 위해 신뢰성 있는 통신을 제공한다. 흐름 제어, 오류 검출 및 재전송을 통해 데이터를 정확하게 전달하며, 속도는 느리지만 신뢰성이 높다.
- UDP (User Datagram Protocol): 비연결 지향형 프로토콜로, 데이터 전송의 보장 없이 빠르게 전송한다. 오류 검출이나 재전송이 없고, 속도가 빠르지만 신뢰성은 낮다. 실시간 스트리밍, 게임 등에 사용된다.


2. IP 주소와 MAC 주소가 필요한 이유

- IP 주소: 네트워크 상에서 장치가 위치한 논리적 주소로, 전 세계적으로 고유하다. 데이터를 목적지 장치까지 라우팅하는 데 사용된다.
- MAC 주소: 네트워크 카드에 할당된 물리적 주소로, 동일 네트워크 내에서 장치를 식별하는 데 사용된다. 같은 네트워크 내에서 장치 간 데이터 전송 시 필요하다.
