### ISSUE TITLE
[OS] 페이지 교체 알고리즘

### ISSUE THREAD

**Issue by LEE-DA-EUN** [kakaotech-25/cs-plant-interview#2]
## 예상 면접 질문

- 페이지 교체 알고리즘에 대해 설명해주세요.
- LRU와 LFU의 차이점에 대해 설명해주세요.

**Comment by JaeJunday** [comment]
1. CPU의 연산속도는 레지스터 => 캐시 => 램 => 디스크 시간 순으로 빠릅니다. 유효주소가 없는 경우 그 다음 저장장치에 가서 내용을 가져옵니다. 램에 디스크의 내용을 바꾸어 올리는것을 페이지 교체라고 부릅니다. 가장 느린 디스크를 참조해야하기 때문에 , 이런 동작이 자주일어나지 않도록 효율적인 알고리즘을 사용해서 성능을 끌어올릴 필요가 있습니다.
2. LRU는 시간이 오래된 부분을 교체하는 방식이고 LFU는 가장 오랫동안 참조되지 않은 부분을 교체하는 방식입니다.

**Comment by rimeir** [comment]
1. 페이지 프로세스가 요구한 페이지가 현재 메모리에 없으면 페이지 부재가 발생하고, 요구한 페이지를 디스크의 스왑 영역에서 메모리로 가져와야 합니다. 그러나 메모리가 이미 가득 차 있다면 추가로 페이지를 메모리에 넣기 위해 기존에 사용하지 않는 페이지를 스왑 영역으로 내보내야 합니다. 이 과정에서 페이지 교체 알고리즘으로 어떤 페이지를 스왑 영역으로 보낼지 결정합니다. 페이지 교체 알고리즘은 페이지의 부재율을 최소화하고 시스템의 전반적인 성능을 최적화하는 데 중점을 둡니다.
2. LRU(Latest Recently Used)는 가장 오랫동안 사용되지 않는 페이지를 스왑 영역으로 이동시키는 알고리즘으로 직전에 참조된 시점만 반영합니다. LFU(Latest Frequently Used)는 페이지 사용 횟수가 가장 적은 페이지를 스왑 영역으로 이동시키는 알고리즘으로 장기적인 참조 성향을 파악할 수 있습니다.

**Comment by msung99** [comment]
1. 페이지 교체 알고리즘이란 스와핑시 스왑 영역으로 보낼 알고리즘을 결정하는 기법으로, 페이지의 부재율을 최소화하여 시스템의 성능을 향상하는 것에 목표를 둡니다.
2. LRU는 최근에 사용되지 않은 페이지를 교체하는 반면, LFU는 사용 빈도가 낮은 페이지를 교체합니다. LRU는 페이지의 최신 사용 시점을 고려하고, LFU는 참조 횟수를 기반으로 페이지를 관리합니다.
