### ISSUE TITLE
[DB] 트랜잭션 ACID 와 격리수준

### ISSUE THREAD

**Issue by msung99** [kakaotech-25/cs-plant-interview#20]
## 예상 면접 질문

- 트랜잭션 ACID 의 각 성질에 대해 설명해보세요.
- 트랜잭션 격리수준은 왜 필요한가요? 애플리케이션에서 격리수준을 고려한 설계를 진행함으로써 얻는 이점이 무엇인가요?
- 각 격리수준 4가지에 대해 설명해보세요. 또한 각 격리수준에서 발생할 수 있는 문제점에는 무엇이 있나요?

## 관련 자료

https://haon.blog/database/transaction-isolation-level/

**Comment by LEE-DA-EUN** [comment]
1. 트랜잭션 ACID 의 각 성질에 대해 설명해보세요.
- **Atomicity (원자성)** : 트랜잭션의 모든 작업이 성공적으로 완료되거나, 전부 취소되어야 함을 의미, 트랜잭션 중 일부만 적용되는 상황은 허용되지 않으며, 실패 시 전체 작업이 롤백
- **Consistency (일관성)** : 트랜잭션이 완료된 후에도 데이터베이스는 일관성 있는 상태를 유지해야 함, 트랜잭션의 실행 전후로 데이터의 무결성이 보장되어야 하며, 모든 제약 조건이 충족된 상태로 유지되어야 함
- **Isolation (고립성)** : 트랜잭션은 독립적으로 실행되어야 하며, 중간 상태가 다른 트랜잭션에 노출되지 않아야 함, 이를 통해 트랜잭션 간의 간섭을 방지
- **Durability (지속성)** : 트랜잭션이 성공적으로 완료되면 그 결과는 영구적으로 저장되어야 함, 시스템 장애가 발생해도 변경 사항은 손실되지 않고 유지됨

2. 트랜잭션 격리수준은 왜 필요한가요? 애플리케이션에서 격리수준을 고려한 설계를 진행함으로써 얻는 이점이 무엇인가요?
동시성 제어를 위해 필요함, 여러 트랜잭션이 동시에 수행될 때, 서로의 작업이 간섭하지 않도록 보장하며 성능과 데이터 일관성 간의 균형을 맞춤
애플리케이션 격리수준을 고려한 설계를 진행함으로써 얻는 이점으로는 데이터 일관성 보장, 성능 최적화, 데드락 방지 등이 있음

3. 각 격리수준 4가지에 대해 설명해보세요. 또한 각 격리수준에서 발생할 수 있는 문제점에는 무엇이 있나요?
- **1. READ UNCOMMITED (커밋되지 않은 읽기)**
- 트랜잭션이 커밋되지 않은 데이터도 다른 트랜잭션에서 읽을 수 있는 가장 낮은 격리 수준
- 문제점 : 더티 리드, 팬텀 리드, Non-Repeatable Read

- **2. READ COMMITED**
- 한 트랜잭션의 변경 내용 중에 커밋이 완료된 데이터만 다른 트랜잭션에서 조회 가능한 격리 수준
- 문제점 : 팬텀 리드, Non-Repeatable Read

- **3. REPEATABLE READ**
- 트랜잭션이 시작되기 전에 커밋된 내용에 대해서만 조회할 수 있는 격리 수준
- 문제점 : 팬텀 리드

- **4. SERIALIZABLE**
- 한 트랜잭션에서 사용되고 있는 데이터는 다른 트랜잭션에서 절대 접근할 수 없는 격리수준
- 다른 트랜잭션이 현재 트랜잭션에 해당되는 데이터에 대한 조회 및 수정 모두 불가능 (데드락 위험)

**Comment by 1013115** [comment]
1. 트랜잭션 ACID 의 각 성질에 대해 설명해보세요.
- 원자성(Atomicity)
 : all or nothing으로 한 트랜잭션내에 담긴 모든 연산들은 데이터베이스에 모두 정상 반영되던지, 또는 전혀 반영되지 않는 것을 보장하는 특징이다. 즉, 트랜잭션을 구성하는 모든 연산 전체가 성공(commit) 또는 실패하는 것(rollback)을 보장하는 특징이다.
- 일관성(Consistency)
: 시스템에 가지고있는 고정 요소는 트랜잭션 수행전과 트랜잭션 수행 완료후에 상태가 일관적으로 같아야한다
- 격리성(Isolation)
: 둘 이상의 트랜잭션이 동시에 수행되는 경우, 실행중인 트랜잭션의 중간 결과에 또 다른 트랜잭션이 접근할 수 없다
- 영구성(Durability)
: 성공적으로 완료(Commit)된 트랜잭션의 결과는 시스템이 고장나더라도 영구적으로 반영되어야 한다

2. 트랜잭션 격리수준은 왜 필요한가요? 애플리케이션에서 격리수준을 고려한 설계를 진행함으로써 얻는 이점이 무엇인가요?
- 멀티 쓰레드 환경일 경우, 각 쓰레드에 의해 트랜잭션이 생성된다. 다시말해, 멀티 쓰레드환경에서 동시간대에 트랜잭션이 생성될 수 있으며, 생성된 여러 트랜잭션들이 동시간대에 공유 자원에 접근하여 동시성 이슈가 발생할 수 있기 때문이다. 격리수준을 고려한 설계를 진행하면서 공유 자원 접근으로 인한 동시성 제어, 동시성 제어시 성능 저하를 최소화할 수 있다.

3. 각 격리수준 4가지에 대해 설명해보세요. 또한 각 격리수준에서 발생할 수 있는 문제점에는 무엇이 있나요?
- READ UNCOMMITED (커밋되지 않은 읽기) : 더티 리드, Non-Repeatable Read, 팬텀 리드
- READ COMMITED : Non-Repeatable Read, 팬텀 리드
- REPEATABLE READ : 팬텀 리드
- SERIALIZABLE : 다른 트랜잭션이 현재 트랜잭션에 해당되는 데이터에 대한 조회 및 수정 모두 불가능 (데드락 위험)

**Comment by rimeir** [comment]
1. 트랜잭션의 ACID 성질은 각각 원자성(Atomicity), 일관성(Consistency), 격리성(Isolation), 지속성(Durability)을 나타냅니다. 원자성은 트랜잭션을 구성하는 모든 연산 전체가 성공하거나 실패하는 것을 보장하는 성질입니다. 일관성은 시스템에 가지고있는 고정 요소는 트랜잭션 수행 전과 수행 완료 후에 상태가 일관적인 성질입니다. 격리성은 실행중인 트랜잭션의 중간 결과에 또 다른 트랜잭션이 접근할 수 없다는 성질입니다. 영구성은 성공적으로 완료된 트랜잭션의 결과는 시스템이 고장나더라도 영구적으로 반영되어야 한다는 성질입니다.
2. 격리수준은 트랜잭션의 ACID를 보장하면서도 각 트랜잭션간의 공유 자원 접근으로 인한 동시성 제어, 동시성 제어시 성능 저하를 최소화합니다. 따라서 애플리케이션이 멀티 스레드 환경일 경우 각 스레드에 의해 동시간대에 트랜잭션이 생성되어 공유 자원을 접근하는 동시성 문제를 해결할 수 있습니다.
3. 격리수준은 READ UNICOMMITED (커밋되지 않은 읽기), READ COMMITED (커밋된 읽기), REPREATABLE READ (반복 가능한 읽기), SERIALIZABLE (직렬화 기능)로 분류됩니다. 
    READ UNICOMMITED (커밋되지 않은 읽기)은 다른 트랜잭션에서 커밋도 안된 해당 변경사항을 읽어와버릴 수 있는 격리수준으로 안정성은 낮지만 성능은 가장 빠릅니다. 발생할 수 있는 문제점으로는 더티 리드, 반복 불가능한 조회, 팬텀 리드가 있습니다. 
    READ COMMITED (커밋된 읽기)은 한 트랜잭션의 변경 내용 중에 커밋이 완료된 데이터만 다른 트랜잭션에서 조회 가능한 격리수준으로 가장 많이 사용됩니다. 발생할 수 있는 문제점으로는 반복 불가능한 조회, 팬텀 리드가 있습니다. 
    REPREATABLE READ (반복 가능한 읽기)은 트랜잭션이 시작되기 전에 커밋된 내용에 대해서만 조회할 수 있는 격리 수준으로 트랜잭션 범위 내에서 조회한 내용이 항상 동일함을 보장하며, 다른 트랜잭션은 트랜잭션 영역에 해당되는 데이터에 대한 수정이 불가능합니다. 발생할 수 있는 문제점으로는 팬텀 리드가 있습니다. 
    SERIALIZABLE (직렬화 기능)은 한 트랜잭션에서 사용되고 있는 데이터는 다른 트랜잭션에서 절대 접근할 수 없는 격리수준으로 가장 안전한 격리수준입니다. 발생할 수 있는 문제점으로는 다른 트랜잭션이 현재 트랜잭션의 데이터 조회 및 수정이 불가능하여 데드락의 위험이 있습니다.

**Comment by JaeJunday** [comment]
## 1. ACID 
  - atomicity : 트랜잭션이 실패하면 전부 실패하거나 다같이 성공해야함
  - consistency : 트랜잭션 전 / 후가 정확해야함
  - isolaton : 트랜잭션 실행 도중 다른 트랜잭션이 실행되지 않아야함
  - durability : 트랜잭션의 결과가 영구적으로 반영되어야함
## 2. 격리
- 동시성 제어, 더티 리드, 반복되지 않는 리드, 팬텀 리드와 같은 동시성 문제가 발생하지 않도록 트랜잭션 간의 격리를 제공합니다.
 ## 3. 격리수준
   - READ UNICOMMITED (커밋되지 않은 읽기) 
   - READ COMMITED (커밋된 읽기) 
   - REPREATABLE READ (반복 가능한 읽기)
   - SERIALIZABLE (직렬화 기능)
