### ISSUE TITLE
[Network] DNS / CA

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/cs-plant-interview#21]
## 예상 면접 질문

- DNS는 왜 사용하나요?
- 웹 통신 흐름에서 CA가 하는 역할은 무엇인가요? 

[DNS](https://github.com/kakaotech-25/cs-plant-interview/blob/main/OS/DNS%20(Domain%20Name%20System)%20e62040fbd7254c88a782a7fa75913d15.md)
[CA](https://github.com/kakaotech-25/cs-plant-interview/blob/main/OS/CA%20(Certificate%20Authority)%20d15e68f3a567416c98dca305077214a9.md)

**Comment by LEE-DA-EUN** [comment]
1. DNS는 왜 사용하나요?
- 유저가 도메인을 사용하여 IP주소를 몰라도 웹 페이지에 접근할 수 있도록 하기 위해 사용함
 
2. 웹 통신 흐름에서 CA가 하는 역할은 무엇인가요?
- CA는 웹 통신에서 SSL/TLS 인증서를 발급하여 웹사이트가 신뢰할 수 있는 사이트임을 보증하고, 데이터 암호화를 통해 통신의 기밀성과 무결성을 보장함

**Comment by 1013115** [comment]
1. DNS는 왜 사용하나요?
- 유저가 도메인을 사용할 때, IP주소를 몰라도 웹 페이지에 접근하기 위해 사용되었음
2. 웹 통신 흐름에서 CA가 하는 역할은 무엇인가요?
- 신뢰할 수 있는 인증서를 발급하여 서버와 클라이언트 간의 안전한 통신을 보장하는 역할을 한다.

**Comment by rimeir** [comment]
1. 유저가 IP 주소를 몰라도 웹페이지에 접근할 수 있어 사용합니다.
2. SSL/TLS 인증서를 발급하고 신뢰성을 검증하여 웹 통신이 안전하고 신뢰할 수 있는 상태로 만듭니다.

**Comment by msung99** [comment]
1. DNS 사용 이유
- DNS(Domain Name System)는 도메인 이름을 IP 주소로 변환해준다. 사람들이 기억하기 쉬운 도메인 이름을 사용해 웹사이트에 접근하면, DNS가 해당 도메인 이름을 서버의 IP 주소로 변환하여 연결을 돕는다. 쉽게 말해, 사람이 읽을 수 있는 주소를 컴퓨터가 이해할 수 있는 주소로 변환하는 시스템이다.

2. CA의 역할
- CA(Certificate Authority, 인증 기관)는 디지털 인증서를 발급하여 웹사이트가 신뢰할 수 있는 사이트임을 증명한다. 브라우저와 서버 간의 SSL/TLS 암호화 통신을 위해 신뢰할 수 있는 공개 키를 제공하며, 중간자 공격을 방지하고 안전한 데이터 통신을 보장하는 역할을 한다.
