### ISSUE TITLE
[DB] 정규화

### ISSUE THREAD

**Issue by 1013115** [kakaotech-25/cs-plant-interview#22]
## 예상 면접 질문

- 데이터베이스 설계에서 정규화는 왜 필요할까요?
- 실무에서는 정규화된 데이터베이스를 그대로 사용하는 것이 항상 최선은 아닐 수 있습니다. 실무에서 정규화를 적용할 때 고려해야할 점에 대해 이야기해보세요.
- binary relation은 항상 BCNF를 만족하는가? 그 이유도 함께 설명해주세요.

**Comment by LEE-DA-EUN** [comment]
1. 데이터베이스 설계에서 정규화는 왜 필요할까요?
- 데이터베이스 내의 중복 데이터와 이상 현상을 반지하기 위해 필요함, 정규화를 통해 데이터 삽입, 삭제, 갱신 시 발생할 수 있는 불일치와 중복을 줄여 데이터의 무결성을 유지할 수 있음

2. 실무에서는 정규화된 데이터베이스를 그대로 사용하는 것이 항상 최선은 아닐 수 있습니다. 실무에서 정규화를 적용할 때 고려해야할 점에 대해 이야기해보세요.
- 실무에서는 정규화가 지나치면 성능 저하가 발생할 수 있음, 정규화로 인해 조인 연산이 많아지거나 데이터의 접근 속도가 느려질 수 있기 때문에 성능과 복잡성을 고려해 비정규화와의 균형을 맞추는 것이 중요함

4. binary relation은 항상 BCNF를 만족하는가? 그 이유도 함께 설명해주세요.
- binary relation은 항상 BCNF를 만족함. 그 이유는 두 속성 중 하나가 반드시 후보키가 되어 다른 속성을 결정하는 구조이기 때문
- BCNF는 모든 결정자가 후보키일 때 만족하는 데, binary relation에서는 하나의 속성이 다른 속성을 결정하므로 자연스럽게 이 조건이 충족됨

**Comment by rimeir** [comment]
1. 데이터베이스 내의 중복 데이터와 이상 현상을 방지하기 위해 필요합니다. 정규화를 통해 데이터의 삽입, 삭제, 갱신 시 발생할 수 있는 불일치와 중복을 줄여 데이터의 무결성을 유지할 수 있습니다.
2. 과도한 정규화는 데이터 조작이 복잡해지고 요지보수가 어려워지며 조회 성능이 떨어질 수 있습니다. 따라서 정규화와 비정규화의 절충을 통해 정규화로 데이터 모델을 최적화 하고, 비정규화로 성능을 개선할 수 있습니다.
3. Binary relation(이항 관계)은 두개의 속성으로 구성되어 모든 결정자가 후보키 집합에 속해 항상 BCNF를 만족합니다.

**Comment by msung99** [comment]
1. 정규화가 필요한 이유
- 정규화는 **중복 데이터를 줄이고, 이상 현상(anomalies)**을 방지하기 위해 데이터베이스를 구조화하는 과정이다. 이를 통해 데이터 무결성 유지, 저장 공간 절약, 그리고 데이터 업데이트 시 발생할 수 있는 문제를 방지한다.

2. 실무에서 정규화 적용 시 고려할 점
- 실무에서는 성능도 중요한 요소이다. 정규화된 데이터베이스는 많은 테이블로 나뉘므로 JOIN 연산이 많아져 성능 저하를 초래할 수 있다. 따라서 읽기 성능이 중요한 경우에는 부분적인 비정규화를 통해 성능을 개선하기도 한다. 따라서 정규화와 성능 간의 균형이 중요하다.

3. Binary relation은 항상 BCNF를 만족하는가?
- binary relation(두 속성만 가진 테이블)은 항상 BCNF를 만족한다. 이유는 BCNF는 모든 결정자가 후보 키여야 하는데, 두 속성만 있는 경우 하나의 속성이 다른 속성을 결정할 때 반드시 후보 키가 되기 때문이다.

**Comment by JaeJunday** [comment]
## 데이터베이스 설계에서 정규화는 왜 필요할까요?
- 중복데이터로 인한 불일치 문제 방지 (정합성)
## 실무에서는 정규화된 데이터베이스를 그대로 사용하는 것이 항상 최선은 아닐 수 있습니다. 
- 정규화 단계가 많아질수록 여러 테이블을 함께 묶어서 가져오는 join연산등이 필요해지는데 이때 성능이 저하 될 수 있습니다. 
- 통상적으로 3.5단계로 불리는 bcnf 정규화 단계까지 많이 사용합니다.
## binary relation은 항상 BCNF를 만족하는가? 그 이유도 함께 설명해주세요.
- 모든 결정자가 슈퍼키 혹은 후보키여야하는데, A->B인경우 B->A인경우 A--B 인경우 모두 만족하기 때문에 BCNF를 항상 만족합니다.
