### ISSUE TITLE
[자료구조] 힙

### ISSUE THREAD

**Issue by Do-yoon** [kakaotech-25/cs-plant-interview#25]
## 예상 면접 질문

- 힙의 정의와 종류를 말해보세요.
- 삽입과 삭제 시 이루어지는 과정에 대해 설명해보세요.

**Comment by JaeJunday** [comment]
힙은 완전 이진트리의 일종으로 최대힙과 최소힙이 있습니다. 또 다른 특징으로는 중복값을 허용한다는 특징이 있습니다.
삭제시엔, 루트노드를 제거하고 균형을 맞춥니다.
삽입시엔, 단말노드에 추가하고 균형을 맞춥니다.

**Comment by 1013115** [comment]
- 힙은 완전 이진트리 기반의 자료주고이며,힙에 어떤 값이 들어와도 특정 힙의 규칙을 지켜지게 만들어져있습니다. 힙에는  최대힙과 최소힙이 존재합니다.
- 삽입시에는, 힙의 리프 노드에 이어서 삽입하고 부모 노드들과의 크기를 비교하고 교환해서 힙의 성질을 유지합니다. 삭제시에는, 루트노드가 삭제되고, 마지막 노드와 루트노드를 스왑하는 과정을 거쳐 재구성됩니다.

**Comment by rimeir** [comment]
1. 힙은 완전 이진 트리 기반의 자료구조로 최대힙과 최소힙이 있습니다. 최대힙은 루트 노드에 있는 키는 모든 자식에 있는  키 중에서 가장 커야하며 각 노드의 자식 노드와의 관계도 이와 같은 특징이 재귀적으로 이루어져야합니다. 최소힙은 루트 노드에 있는 키는 모든 자식에 있는 키 중에서 최솟값이어야 하며 각 노드의 자식 노드와의 관계도 이와 같은 특징이 재귀적으로 이루어져야합니다.
2. 최대힙에서 힙에 새로운 요소가 들어오면 새로운 노드를 힙의 마지막 노드에 이어서 삽입합니다. 이러한 새로운 노드를 부모 노드들과의 크기를 비교하며 교화하여 힙의 성질을 만족시킵니다. 최대힙에서 최댓값은 루트 노드로 루트 노드가 삭제되고 이후 마지막 노드와 루트 노드를 스왑하여 다시 스왑 등의 과정을 거쳐 재구성된다.

**Comment by LEE-DA-EUN** [comment]
1. 힙의 정의와 종류를 말해보세요.
힙은 완전 이진 트리 기반의 자료구조이며 최소힙과 최대힙 두 가지가 있고 해당 힙에 따라 특정한 특징을 지킨 트리를 말한다. 최대힙은 루트 노드에 있는 키는 모든 자식에 있는 키중에서 가장 커야 하고 각 노드의 자식 노드와의 관계도 이와 같은 특징이 재귀적으로 이루어져야 한다. 최소힙은 루트 노드에 있는 키는 모든 자식에 있는 키 중에서 최솟값이어야 하고, 각 노드의 자식 노드와의 관계도 이와 같은 특징이 재귀적으로 이루어져야 한다.

2. 삽입과 삭제 시 이루어지는 과정에 대해 설명해보세요.
최대힙의 삽입 시에는 새로운 요소가 들어오면, 일단 새로운 노드를 힙의 마지막 노드에 이어서 삽입한다. 이 새로운 노드를 부모 노드들과의 크기를 비교하며 교환해서 힙의 성질을 만족시킨다. 삭제 시에는 최대힙의 최댓값은 루트 노드이므로 루트노드가 삭제되고 그 이후 마지막 노드와 루트노드를 스왑하여 또다시 스왑 들의 과정을 거쳐 재구성된다.
