### ISSUE TITLE
[자료구조] DFS & BFS

### ISSUE THREAD

**Issue by rimeir** [kakaotech-25/cs-plant-interview#26]
## 예상 면접 질문

- DFS와 BFS는 각각 어떤 자료구조를 사용하나요?
- DFS와 BFS의 동작 방식에 대해 설명하고 둘의 차이점을 설명해주세요.
- DFS와 BFS는 각각 어떤 상황에서 사용하는 것이 적합한가요?

**Comment by JaeJunday** [comment]
DFS는 스택, BFS는 큐를 사용합니다.
DFS는 한쪽노드 끝까지 깊이우선탐색을 진행하고, BFS는 주변 노드순서로 너비우선 탐색을 합니다.
DFS는 모든 경로 탐색문제, BFS는 최단경로 탐색문제에 적합합니다.

**Comment by 1013115** [comment]
- dfs는 스택, bfs는 큐를 사용합니다.
- dfs는 그래프에서 깊은 부분을 우선 탐색하고 bfs는 너비 우선 탐색을 진행합니다.  dfs는 모든 경로를 끝까지 탐색하여 목표를 찾을 때까지 경로를 계속 탐색하고 특정 경로에서 목표를 빨리 찾을 수 있지만 목표를 찾았더라도 최단 경롤르 보장하지 않습니다. bfs는 같은 레벨의 노드를 모두 탐색한 후에 그 다음 레벨의 노드를 탐색합니다.
- dfs는 모든 경로를 탐색하는 경우, bfs는 최단 경로 탐색에 유리합니다.

**Comment by LEE-DA-EUN** [comment]
1. DFS와 BFS는 각각 어떤 자료구조를 사용하나요?
- DFS는 스택 또는 재귀 함수를 이용하여 노드 탐색을 한다.
- BFS는 큐를 이용하여 노드 탐색을 한다.

2. DFS와 BFS의 동작 방식에 대해 설명하고 둘의 차이점을 설명해주세요.
- DFS는 깊이 우선 탐색으로 스택 동작원리와 동일하게 탐색 시작 노드를 스택에 삽입하고 방문 처리한다. 이후 스택의 최상단 노드에 방문하지 않은 인접노드가 있으면 그 인접 노드를 스택에 넣고 방문 처리한다. 방문하지 않은 인접 노드가 없을 경우에는 스택에서 최상단 노드를 꺼낸다. 이 과정을 더 이상 수행할 수 없을 때까지 반복한다.
- BFS는 너비 우선 탐색으로 큐의 동작원리와 동일하게 탐색 시작 노드를 큐에 삽입하고 방문 처리한다. 큐에서 노드를 꺼내 해당 노드의 인접 노드 중에서 방문하지 않은 노드를 모두 큐에 삽입하고 방문 처리한다. 이 과정을 더 이상 수행할 수 없을 때까지 반복한다.

3. DFS와 BFS는 각각 어떤 상황에서 사용하는 것이 적합한가요?
- DFS는 모든 경로를 탐색해야 할때 사용하고, BFS는 최단 경로를 탐색해야 할때 사용한다.
