### ISSUE TITLE
[DB] 인덱스

### ISSUE THREAD

**Issue by msung99** [kakaotech-25/cs-plant-interview#27]
## 예상 면접 질문

- 인덱스란 무엇이며, 왜 사용하는가?
- 인덱스를 항상 모든 테이블에 적용하면 안되는가? 모든 테이블에 적용해버릴 경우 생기는 문제점은 무엇인가?
- 인덱스 자료구조으 종류로는 무엇이 있는가? 그리고 어떤 장점으로 인해 현재 대부분의 DBMS 에서 B+ Tree 구조를 택하게 됐는가?
- 만약 USER 테이블 내의 컬럼에 성별  컬럼, 그리고 주민등록번호 컬럼이 있다고해보자. 둘 중 카디널리티가 더 높은 컬럼은 무엇일까?

## 참고 자료

- https://haon.blog/database/index-basic/

**Comment by JaeJunday** [comment]
- 데이터 베이스의 검색성능을 향상 시키기 위해서 사용하는 자료구조 입니다. 중복제거와 정렬에 탁월합니다.
- 인덱스도 데이터와 같이 관리되기 때문에, 쓰기성능과 저장공간이 낭비됩니다.
- B tree, 해시 인덱스, 트라이 등등, 성능을 최적화하려면 가장 오래걸리는부분을 해결해야하는데, 일반적으로 디스크는 접근 속도 자체가 느리기 때문에 최대한 한 차수에 많은 데이터를 집어넣도록 B+tree를 선택한것으로 이해하고 있습니다.
- 카디널리티는 한 컬럼이 가질 수 있는 고유한 값의 수를 의미하기 때문에 주민등록번호 컬럼이 더 높습니다.

**Comment by 1013115** [comment]
- 데이터베이스에서 인덱스는 빠른 조회 성능을 위해 미리 저장해놓은 추가적인 공간이다. 인덱스를 사용하면 디스크에 접근하여 수행하는 불필요한 I/O를 최소화하여, 데이터 탐색 성능을 개선할 수 있다.
- 데이터베이스 내에 인덱스가 생성되는 특정 공간이 고정되어있는데 이 크기가 매우 작으므로 잘못 사용한다면 불필요한 저장 공간을 낭비할 수 있다.
- 해시테이블, B - tree, B+ tree 등이 존재한다. B+ tree는 B tree에서 개선된 구조로 리프노드끼리 서로를 포인터로 연결하는 링크드 리스트 구조를 취한다. 이 링크드리스트 구조로 인해 범위 탐색의 성능이 빨라진다.
- 카디널리티는 데이터 집합에서 유일한 데이터 개수를 뜻하므로 주민등록번호가 단 1명의 사람에게 보장되는 유일성을 가지기 때문에 카디널리티가 더 높다.

**Comment by LEE-DA-EUN** [comment]
1. 인덱스란 무엇이며, 왜 사용하는가?
- 데이터베이스 인덱스란 빠른 조회 성능을 위해 미리 저장해놓은 추가적인 저장 공간이다. 내가 원하는 특정 데이터를 빠르게 탐색하기 위해 미리 정렬해놓은 인덱스 정보를 활용할 수 있다. 인덱스를 통해 원하는 데이터가 저장소 내부 어디에 있는지의 정보를 빠르게 서칭하고 해당 페이지로 이동하여 데이터를 조회할 수 있다.

2. 인덱스를 항상 모든 테이블에 적용하면 안되는가? 모든 테이블에 적용해버릴 경우 생기는 문제점은 무엇인가?
- 인덱스를 생성하면 아무곳에나 생성되는 것이 아니라 데이터베이스 내에서 인덱스가 생성되는 특정 공간이 고정되어있다. 이 저장 공간은 데이터베이스 전체 공간에서 약 10% 만을 허용한다. 즉, 인덱스를 생성할 수 있는 저장공간의 크기는 매우 작기 때문에 잘못 사용하면 불필요한 저장 공간을 낭비할 수 있다.

3. 인덱스 자료구조으 종류로는 무엇이 있는가? 그리고 어떤 장점으로 인해 현재 대부분의 DBMS 에서 B+ Tree 구조를 택하게 됐는가?
- 인덱스를 저장하는 자료구조의 종류로는 해싱, B- Tree, B+ Tree 등이 있다. 
- 해시 테이블 : 키-밸류 형태로 데이터를 저장하는 자료구조이다. 데이터의 키 값을 알고 있다면 데이터에 O(1) 라는 빠른 시간복잡도로 접근할 수 있지만 대소비교 연산으로 인해 느리다는 단점이 있다.
- B- Tree : 이진트리와 달리 자식 노드를 여러 개 가질 수 있는 균형 트리 구조이다. 이진 탐색 트리에서 노드의 개수를 늘리고 전체 높이를 줄임으로써 매우 빠른 탐색 성능을 얻을 수 있다.
- B+ Tree : B- Tree에서 개선된 구조로 대부분의 DBMS에서 채택중인 자료구조, 리프 노드끼리 서로를 포인터로 연결하는 링크드 리스트 구조를 취한다. 이로 인해 범위 탐색의 성능이 매우 빠르다.
- 결론 : B+ Tree 는 B- Tree와 달리 리프 노드끼리 링크드 리스트를 취하기 때문에 1개가 아닌 여러 데이터를 조회하는 레인지 스캔, 즉 범위 스캔이 유리하다. 그래서 대부분 B+ Tree를 선택하고 있다.

4. 만약 USER 테이블 내의 컬럼에 성별 컬럼, 그리고 주민등록번호 컬럼이 있다고해보자. 둘 중 카디널리티가 더 높은 컬럼은 무엇일까?
- 카디널리티란 데이터 집합에서 유일한 데이터 개수를 뜻한다. 즉, 데이터 특성상 유일성이 높은 컬럼일수록 인덱싱해주는 게 좋다. 주민등록번호는 단 1명의 사람에게 보장되는 유일성을 가지기 때문에 카디널리티가 높다.
