### ISSUE TITLE
[네트워크] 로드밸런싱

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/cs-plant-interview#29]
## 예상 면접 질문

[로드밸런싱 보러가기](https://github.com/kakaotech-25/cs-plant-interview/blob/main/Network/%EB%A1%9C%EB%93%9C%EB%B0%B8%EB%9F%B0%EC%8B%B1.md)

- 로드밸런싱(부하분산)이란 무엇인가요?
- L4 로드밸런싱과 L7 로드밸런싱의 차이를 말해주세요.

**Comment by 1013115** [comment]
- 서버에 가해지는 트래픽이나 작업 부하를 여러 서버로 분산시켜 각 서버의 부담을 줄이는 것을 말합니다.
- L4 로드밸런싱은 IP 주소와 포트 번호 등의 전송계층 정보를 기반으로 트래픽을 분산합니다. L7 로드밸런싱은 HTTP 해더, 쿠키, URL 패턴 등의 애플리케이션 계층 정보를 기반으로 트래픽을 분산합니다. L4 로드밸런싱은 빠른 처리 속도와 낮은 지연시간을 가지고 세션 정보를 유지하지 않으르모 stateless 방식입니다. L7로드밸런싱의 경우는 session sticky 등 세션 유지가 가능하고 콘텐츠 기반 라우팅이 가능하여 특정 요청을 특정 서버로 전달이 가능합니다.

**Comment by LEE-DA-EUN** [comment]
1. 로드밸런싱(부하분산)이란 무엇인가요?
- 로드밸런싱이란 서버에 가해지는 트래픽이나 작업 부하를 여러 서버로 분산시켜 각 서버의 부담을 줄이는 것이다.

2. L4 로드밸런싱과 L7 로드밸런싱의 차이를 말해주세요.
- L4 로드밸런싱은 IP주소와 포트번호 등의 전송 계층 정보를 기반으로 트래픽을 분산시키는 반면, L7 로드밸런싱은 HTTP 헤더, 쿠키, URL패턴 등의 애플리케이션 계층 정보를 기반으로 트래픽을 분산시킨다.
- L4 로드밸런싱은 빠른 처리 속도와 낮은 지연 시간, 세션 정보를 유지하지 않아 무상태 방식에 적합한 반면, L7 로드밸런싱은 세션 스티키 등 세션 유지가 가능하고 콘텐츠 기반 라우팅이 가능하여 특정 요청을 틍정 서버로 전달 가능하다.

**Comment by rimeir** [comment]
1. 로드밸런싱은 서버에 가해지는 트래픽이나 작업을 여러 서버로 분산시키는 네트워크 기술입니다.
2. L4 로드밸런싱은 IP 주소와 포트 번호 등의 전송 계층 정보를 기반으로 트래픽을 분산합니다. L4 로드밸런싱은 처리 속도가 빠르고 지연 시간이 낮습니다. 또한 세션 정보를 유지하지 않아 무상태 방식으로 진행합니다.  L7 로드밸런싱은 HTTP 헤더, 쿠키, URL 패턴 등의 애플리케이션 계층 정보를 기반으로 트래픽을 분산합니다. 세션 스티키 등 세션 유지가 가능하고 콘텐츠 기반 라우팅이 가능하여 특정 요청을 특정 서버로 전달할 수 있습니다.
