### ISSUE TITLE
[DB] 키(key)

### ISSUE THREAD

**Issue by 1013115** [kakaotech-25/cs-plant-interview#30]
## 예상 면접 질문

- 외래 키 제약조건을 위반하는 경우 어떤 문제가 발생할 수 있나요?
- NULL 값을 허용할 수 있는 키는 무엇인가요?
- 복합 키(Composite Key)의 장단점은 무엇인가요?

**Comment by JaeJunday** [comment]
- 외래키 제약조건을 위반하면 데이터베이스의 무결성과 일관성이 떨어질 수 있습니다. 
- 외래키의 경우 부모테이블을 참조하지 않을 수 있기 때문에 NULL값이 허용됩니다.
- 복합키 자체가 데이터를 가져오는 의미가 되기때문에 자연스러운 식별자가 될수있지만, 인덱싱을 복합적으로 진행하기 때문에 관리하기가 까다롭고 성능이 저하될 수 있습니다.

**Comment by LEE-DA-EUN** [comment]
1. 외래 키 제약조건을 위반하는 경우 어떤 문제가 발생할 수 있나요?
- 외래키의 제약조건을 위반하는 경우에는 데이터베이스의 참조 무결성 유지에 문제가 발생할 수 있다.

2. NULL 값을 허용할 수 있는 키는 무엇인가요?
- 슈퍼 키는 유일성은 보장하지만 최소성은 보장하지 않기 때문에, NULL 값을 가질 수 있는 속성들이 포함될 수 있다.

3. 복합 키(Composite Key)의 장단점은 무엇인가요?
- 장점 : 단일 컬럼으로는 유일성을 보장할 수 없을 때 여러 컬럼을 결합하여 복합키로 사용할 수 있다.
- 단점 : 너무 많은 컬럼을 포함하면 성능에 영향을 줄 수 있다. -> 필요최소한의 컬럼으로 구성하는 것이 좋다.
