### ISSUE TITLE
[OS] 세마포어 & 뮤텍스

### ISSUE THREAD

**Issue by 1013115** [kakaotech-25/cs-plant-interview#5]
## 예상 면접 질문

- 세마포어와 뮤텍스의 차이점은?
- 세마포어는 어떻게 나뉘는지

**Comment by JaeJunday** [comment]
세마포어는 자원에 접근하는 프로세스의 수를 제한할 수 있고, 뮤텍스는 하나의 프로세스가 자원에 접근하는것을 보장합니다.

**Comment by LEE-DA-EUN** [comment]
1. 세마포어와 뮤텍스의 차이점은?
- **뮤텍스**는 상호 배제의 약어로 잠금을 획득한 다음 잠금을 해제하여 중요한 섹션만 보호한다. 뮤텍스는 *단 하나*의 프로세스/스레드만 접근가능함.
- **세마포어**는 공유된 자원의 데이터 혹은 임계영역에 *여러 개*의 프로세스/스레드가 접근하는 것을 막아줌

2. 세마포어는 어떻게 나뉘는지
- counting 세마포어 : 초기값은 가능한 자원의 수로 정해지며 세마포어의 값의 범위는 정해져 있다.
- Binary 세마포어 : 뮤텍스 락과 동일하고 세마포어 값으로 0 또는 1을 가진다. Test and Set 등 하드웨어가 지원하는 기능을 이용하여 구현하기도 한다.

**Comment by rimeir** [comment]
1. 세마포어는 signaling 메커니즘으로 lock을 걸지 않은 스레드도 signal을 보내 lock을 해제할 수 있다. 뮤텍스는 locking 메커니즘으로 lock을 걸은 오직 하나의 스레드만 동일한 시점에 임계영역에 들어올 수 있으며 임계 영역을 나갈 때 lock을 해제할 수 있다.
2. Binary semaphore(이진 세마포어)와 Counting semaphore(카운팅 세마포어)로 나누어집니다. Binary semaphore는 세마포어 값으로 0 또는 1을 가지며 뮤텍스 lock과 유사하게 동작합니다. Counting semaphore는 세마포어 값의 범위가 따로 정해져 있지 않습니다.

**Comment by msung99** [comment]
- 뮤텍스(Mutex)는 단일 자원에 대해 배타적 접근을 제공하는 동기화 도구로, 한 번에 하나의 스레드만 자원에 접근할 수 있습니다.
- 세마포어(Semaphore)는 카운터를 사용해 여러 스레드가 동시에 자원에 접근할 수 있도록 제어하며, 이진 세마포어와 계수기 세마포어로 나뉩니다.
- 이진 세마포어는 뮤텍스와 유사하게 동작하며, 계수기 세마포어는 여러 자원의 동시 접근을 제어합니다.
