### ISSUE TITLE
[OS] 경쟁조건

### ISSUE THREAD

**Issue by 1013115** [kakaotech-25/cs-plant-interview#7]
## 예상 면접 질문

- 프로세스 동기화에 대해 설명해보시오
- 임계 구역 문제를 해결하기 위한 조건은?

**Comment by LEE-DA-EUN** [comment]
1. 프로세스 동기화에 대해 설명해보시오
- 프로세스 동기화는 프로세스의 실행 순서를 제어하고 동시에 접근할 수 없는 자원에 하나의 프로세스만 접근하게 하여 데이터의 일관성을 유지하는 과정이다.
- 프로세스는 동시에 실행되면서 영향을 주고 받는데 이 과정에서 일관성이 보장되어야 한다.

2. 임계 구역 문제를 해결하기 위한 조건은?
- 상호 배제 : 임계구역에는 한번에 하나의 프로세스만 들어가야 한다. 두 개 이상의 프로세스가 동시에 공유 자원에 접근하여 데이터를 손상시키는 상황을 방지한다.
- 진행 : 임계구역에 들어가려고 하는 프로세스들이 있을 때 선택되지 않은 프로세스들이 무한히 기다리지 않도록 해야 한다. 기다리는 프로세스 중 하나가 반드시 선택되어 임계구역에 들어가도록 한다.
- 한정된 대기 : 프로세스가 임계 구역에 들어가기 위해 기다리는 시간이 무한하지 않도록 보장해야 한다. 특정 프로세스가 무한정 기다리는 상황을 방지해야 한다.

**Comment by rimeir** [comment]
1. 프로세스 동기화는 프로세스의 실행 순서를 제어하고 공유 자원에 하나의 프로세스만 접근할 수 있도록 하여 데이터의 일관성을 유지하는 과정입니다. 여러 프로세스가 동시에 실행되어도 서로 간섭하지 않고 자원의 일관성을 유지하도록 보장해야 합니다.
2. 임계 구역은 경쟁 조건을 발생시킬 수 있는 코드 블록으로 임계 구역 문제를 해결하기 위해서는 상호 배제, 진행, 한정된 대기와 같은 요구사항을 만족해야합니다. 상호 배제는 한 번에 하나의 프로세스만 들어가 두 개 이상의 프로세스가 동시에 공유 자원에 접근하여 데이터를 손상시키는 상황을 방지합니다. 진행은 선택되지 않은 프로세스를 무한히 기다리지 않도록 합니다. 한정된 대기는 프로세스가 무한정 기다리는 상황을 방지합니다.

**Comment by JaeJunday** [comment]
1. 프로세스 동기화는 자원에 프로세스가 접근하는 순서를 보장해서 데이터 일관성을 유지하는 것입니다.
2. 임계 구역 문제는 상호 배제, 진행, 한정된 대기 같은 방식을 사용해서 해결해야하는데, 뮤텍스나 세마포어, 혹은 IPC에 해당하는 모든 도구를 사용하여 해결할 수 있습니다.

**Comment by msung99** [comment]
1. 경쟁상태가 발생하는 특정 조건 또는 영역(임계영역) 에 대해 데이터의 일관성을 해치지 않도록 쓰레드간의 접근 순서를 지정하여 데이터의 무결성을 보장하는 기법이다.
2. 세마포어, 스핀락과 같은 대표적인 기법이 존재한다.  + 추가적으로 스프링부트 내에선 낙관적 락, 비관적 락, 분산 락, 네임드 락 등의 기법이 추가적으로 존재한다.
